databases:
  - name: roma_hair_db
    databaseName: roma_hair
    user: roma_user
    plan: free # Advertencia: Expira en 90 d√≠as. Cambiar a 'starter' para prod real.

services:
  # BACKEND SERVICE
  - type: web
    name: roma-cabello-backend
    env: python
    region: oregon # O la que prefieras
    plan: free
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: roma_hair_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 10
      - key: PYTHON_VERSION
        value: 3.11.0

  # FRONTEND SERVICE
  - type: web
    name: roma-cabello-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL_HOST
        fromService:
          type: web
          name: roma-cabello-backend
          property: host
